name: "Example"
description: "Receives file and generates output"
runs:
  using: "composite"
  steps:
    - run: echo "Hello, World!" > results.txt
      shell: bash

    - id: run-test
      run: |
        node ${{ inputs.file-path }} > ${{ inputs.results-file }}
      shell: bash

    - id: output-results
      run: cat ${{ inputs.results-file }}
      shell: bash
inputs:
  file-path:
    description: "Path to test script"
    required: true
    default: "test-file.js"
outputs:
  results-file:
    description: "Path to results file"
    value: ${{ steps.run-test.outputs.results-file }}