name: "Example"
description: "Receives file and generates output"
runs:
  using: "composite"
  steps:
    - run: echo "Hello, World!" > results.txt
      shell: bash

    - id: run-test
      run: |
        # Adicione seu script de teste aqui
        node ${{ inputs.file-path }} > ${{ inputs.results-file }}
      shell: bash

    - id: output-results
      run: cat ${{ inputs.results-file }}
      shell: bash