name: Access Secret
on: [workflow_dispatch]
jobs:
  access-secret:
    runs-on: ubuntu-latest
    environment: VARIABLES
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Essa ação faz o checkout do código do repositório
      - name: Set up environment variables
        run: |
          echo "MY_SECRET=${{ secrets.NOME }}" >> $GITHUB_ENV
          echo "TESTE=${{ vars.TESTE }}" >> $GITHUB_ENV

      - name: Access TESTE
        run: echo "Hello $TESTE"

      - name: Access MY_SECRET
        run: echo "Hello $MY_SECRET"
    