name: Access Secret
on: [workflow_dispatch]
jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello secret
        run: echo "Hello ${{ secrets.MY_SECRET }}"

      - name: Hello var
        run: echo "Hello ${{ env.TESTE }}"
        env:
          TESTE: ${{ secrets.TESTE }}
