name: Access Secret
on: [push]
jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello secret
        run: echo "Hello ${{ secrets.MY_SECRET }}"