name: Access Secret
on: [push]
jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        env:
          NOME: ${{ secrets.NOME }}
        run: echo "Hello $NOME"