name: Access Secret
on: [push]
jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment variables
        shell: bash
        run: |
          echo "MY_SECRET=${{ secrets.MY_SECRET }}" >> $GITHUB_ENV
          echo "TESTE=${{ secrets.TESTE }}" >> $GITHUB_ENV

      - name: Hello secret
        shell: bash
        run: echo "Hello ${{ env.MY_SECRET }}"

      - name: Hello var
        shell: bash
        run: echo "Hello ${{ env.TESTE }}"
