name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Defina o branch que deve disparar a ação

jobs:
  build:
    runs-on: ubuntu-latest
    environment: VARIABLES
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/agronota-app  # Certifique-se de que o nome do repositório está correto
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: otimizai_agronota_app
          ref: main  # Adicione o branch principal ou específico

      - name: Verify private repository content
        run: |
            echo "Contents of otimizai_agronota_app:"
            ls -la otimizai_agronota_app/otimizai_agronota_app

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.22.2'
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web
        
      - name: Deploy web app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: otimizai_agronota_app/build/web
          publish_branch: gh-pages
          cname: agronota.com.br
          commit_message: 'Deploy Flutter Web App 🚀'



