name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Defina o branch que deve disparar a ação

jobs:
  build:
    runs-on: ubuntu-latest
    environment: VARIABLES
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/agronota-app 
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: otimizai_agronota_app
          ref: main 

      - name: Check current directory inside subdirectory
        working-directory: otimizai_agronota_app/otimizai_agronota_app
        run: |
            pwd
            ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            flutter-version: '3.22.2'

      - name: Flutter build
        working-directory: otimizai_agronota_app/otimizai_agronota_app
        run: |
            flutter pub upgrade --major-versions
            flutter pub get
            flutter build web --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        # Importante: O comando flutter build web --release não é mais necessário
        # e para que o build funcione no GitHub Actions, é necessário ter a pasta web no diretório raiz do projeto

      - name: Check current directory inside subdirectory
        
        run: |
            pwd
            ls -la

      - name: Use Python 3.x
        working-directory: otimizai_agronota_app/otimizai_agronota_app
        run: |
          python -c "import os
          import re
          index_file_path = 'build/web/index.html'
          print(os.system('ls -la'))
          print('+' * 20)
          print(os.system('ls -la build/web'))
          print(os.system('pwd'))
          with open(index_file_path, 'r', encoding='utf-8') as file:
              content = file.read()
          content = re.sub(r'href=\"/*', 'href=\"./', content)
          with open(index_file_path, 'w', encoding='utf-8') as file:
              file.write(content)"

      - name: Deploy web app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LUZ_CAMERA_ACAO_TOKEN }}
          publish_dir: otimizai_agronota_app/otimizai_agronota_app/build/web
          publish_branch: gh-pages
          commit_message: 'Deploy Flutter Web App 🚀'