name: Generate Podcast Feeds
on:
  push:
    branches:
      - linkedin-course
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Podcast Feeds
        run: python feed.py

      # Esses comandos configuram o nome e o email do usuário do Git para o bot do GitHub Actions.
      # O github-actions[bot] é um usuário especial que o GitHub Actions usa para fazer commits e push de mudanças no repositório.
      - name: Commit and Push Changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com
          git add .
          git commit -m "Generate Podcast Feeds"
          git push
