name: Test Cron

on:
  schedule:
    - cron: '*/15 * * * *'  # Cada 5 minutos para teste

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run echo
        run: echo "Hello, World!"
